services:
  nginx:
    image: nginx:1.27.2
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - techfinance
  db:
    image: postgres:17
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    ports:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - techfinance
  app:
    build:
      context: ./app
    container_name: app
    volumes:
      - ./app:/app
    ports:
      - 3000
    environment:
      - DATABASE_URL=postgresql://docker:docker@db:6543/docker
      - AUTHORIZATION=ronaldo
    depends_on:
      db:
        condition: service_healthy
    networks:
      - techfinance

volumes:
  postgres_data:

networks:
  techfinance:
