// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/clientes": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna uma lista de clientes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clientes"
                ],
                "summary": "Retorna uma lista de clientes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nome do cliente",
                        "name": "nome",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Grupo do cliente",
                        "name": "grupo",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limite de registros por página",
                        "name": "limite",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Número da página",
                        "name": "pagina",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Customer"
                            }
                        }
                    }
                }
            }
        },
        "/produtos": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna uma lista de produtos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "produtos"
                ],
                "summary": "Retorna uma lista de produtos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Descrição do produto",
                        "name": "descricao",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Grupo do produto",
                        "name": "grupo",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limite de registros por página",
                        "name": "limite",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Número da página",
                        "name": "pagina",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Product"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Customer": {
            "type": "object",
            "properties": {
                "cidade": {
                    "type": "string"
                },
                "estado": {
                    "type": "string"
                },
                "grupo": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "id_grupo": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "nome_fantasia": {
                    "type": "string"
                }
            }
        },
        "models.Product": {
            "type": "object",
            "properties": {
                "descricao": {
                    "type": "string"
                },
                "grupo": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "id_grupo": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "https://techfinance.fly.dev",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "TechFinance API",
	Description:      "TechFinance é uma solução mobile para para prover informações para apoio para tomada de decisões. Esta é uma API backend construída utilizando o framework **Fiber** (na linguagem Go).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
